/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ProductionCoordinatorRole;

import Ecosystem.EcoSystem;
import Ecosystem.Enterprise.Enterprise;
import Ecosystem.Enterprise.SmartphoneEnterprise;
import Ecosystem.Network.Network;
import Ecosystem.Organization.AssemblyOrganization;
import Ecosystem.Organization.Organization;
import Ecosystem.Organization.ResearchAndDevelopmentOrganization;
import Ecosystem.Product.SmartphoneProduct;
import Ecosystem.Product.SmartphoneProductCatalog;
import Ecosystem.UserAccount.UserAccount;
import Ecosystem.WorkQueue.AssemblyWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sunny
 */
public class RequestAssemblyJPanel extends javax.swing.JPanel {
    private JPanel workArea;
    private UserAccount userAccount;
    private Enterprise assemblyEnterprise;    
    private SmartphoneProductCatalog smartphoneProductCatalog;
    private EcoSystem system;
    
    /**
     * Creates new form RequestAssemblyJPanel
     */
    public RequestAssemblyJPanel(JPanel userProcessContainer, UserAccount account, SmartphoneProductCatalog smartphoneProductCatalog, Enterprise enterprise, EcoSystem ecosystem) {
        initComponents();
        
        this.workArea = userProcessContainer;
        this.userAccount = account;
        this.assemblyEnterprise = assemblyEnterprise;
        this.smartphoneProductCatalog = smartphoneProductCatalog;
        this.system = ecosystem;
        
        populateProductComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMessage = new javax.swing.JTextField();
        lblProduct = new javax.swing.JLabel();
        cbbProduct = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnRequest = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        lblQuant = new javax.swing.JLabel();
        txtQuant = new javax.swing.JTextField();

        lblProduct.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblProduct.setText("Select a product:");

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel10.setText("Send Request Assembly ");

        btnBack.setBackground(new java.awt.Color(255, 153, 153));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnRequest.setText("Request");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });

        lblMessage.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMessage.setText("Message:");

        lblQuant.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblQuant.setText("Quantity:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRequest)
                            .addComponent(lblMessage)
                            .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblProduct)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbbProduct, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblQuant)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProduct)
                    .addComponent(cbbProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuant)
                    .addComponent(txtQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(lblMessage)
                .addGap(18, 18, 18)
                .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnRequest)
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        workArea.remove(this);
        Component[] componentArray = workArea.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ProductionCoordinatorWorkAreaJPanel jPanel = (ProductionCoordinatorWorkAreaJPanel) component;
        jPanel.populateRequestTable();
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed

        String message = txtMessage.getText();
        String quant = txtQuant.getText();
        String productName = cbbProduct.getSelectedItem().toString();

        if(message.equals("") || message.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter something to send.");
            return;
        }
        
        if(cbbProduct.getSelectedItem()==null){
            JOptionPane.showMessageDialog(null, "Please select a product.");
            return;
        }
        
        if(quant.equals("") || quant.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter the product quantity.");
            return;
        }
        
        if(productName.equals("") || productName.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter the product name.");
            return;
        }

        productName = cbbProduct.getSelectedItem().toString();
        AssemblyWorkRequest request = new AssemblyWorkRequest();

        request.setProductName(cbbProduct.getSelectedItem().toString());
        request.setMessage(message);
        request.setProductName(productName);
        request.setProductQuant(Integer.parseInt(quant));
        request.setSender(userAccount);
        request.setStatus("Sent");

        
        Organization org = null;
        for(Network network : system.getNetworkList()){
            for(Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()){
                for (Organization o : e.getOrganizationDirectory().getOrganizationList()){
                        if (o instanceof AssemblyOrganization){
                        org = o;
                        break;
                    }
                }
            }
        }
        
        
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }

        JOptionPane.showMessageDialog(null, "Request message sent");
        cbbProduct.setSelectedItem(null);
        txtMessage.setText("");
        txtQuant.setText("");
    }//GEN-LAST:event_btnRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequest;
    private javax.swing.JComboBox<Object> cbbProduct;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel lblQuant;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JTextField txtQuant;
    // End of variables declaration//GEN-END:variables

    private void populateProductComboBox() {
        for (SmartphoneProduct product : smartphoneProductCatalog.getProductCatalog()){
            cbbProduct.addItem(product);
        }
    }
}
